# Generated by Django 5.0.4 on 2024-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_remove_customuser_watched_list_customuser_watched_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='watched',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
