# Generated by Django 5.0.4 on 2024-05-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_watched_options_favourite_customuser_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='watched',
        ),
        migrations.DeleteModel(
            name='Watched',
        ),
    ]
