# Generated by Django 5.0.4 on 2024-05-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_watched_delete_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favourite',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
