# Generated by Django 5.0.4 on 2024-05-10 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('watched', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watched',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='watched',
            name='unique_movie_user_watched',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='user',
        ),
    ]
