# Generated by Django 5.0.4 on 2024-05-10 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('watched', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watched',
        ),
    ]
