# Generated by Django 5.0.4 on 2024-05-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watched', '0002_alter_watched_options_and_more'),
        ('watched', '0003_initial'),
    ]

    operations = [
    ]
