# Generated by Django 5.0.4 on 2024-05-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watched', '0004_merge_20240510_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watched',
        ),
    ]
