# Generated by Django 5.0.4 on 2024-05-09 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rate',
        ),
    ]
