# Generated by Django 5.0.4 on 2024-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cosine_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
    ]
