# Generated by Django 5.0.4 on 2024-05-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_system', '0002_cosine_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cosine_model',
            new_name='CosineModel',
        ),
    ]
