# Generated by Django 5.0.4 on 2024-05-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_system', '0004_movierecommend_movierecommend_unique_movie_recommend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRecommend',
        ),
    ]
