# Generated by Django 5.0.4 on 2024-06-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_system', '0006_movierecommend_movierecommend_unique_movie_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountVectorizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
    ]
