# Generated by Django 5.0.4 on 2024-06-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_system', '0007_countvectorizer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountVectorizer',
            new_name='CountVectorizerModel',
        ),
    ]
