# Generated by Django 5.0.4 on 2024-06-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webjob', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestWJob',
        ),
    ]
