# Generated by Django 5.0.4 on 2024-04-28 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('genres', '0001_initial'),
        ('movies', '0009_alter_movies_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genrers',
            new_name='Genre',
        ),
    ]
