# Generated by Django 5.0.4 on 2024-05-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_alter_genre_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('id',)},
        ),
    ]
