# Generated by Django 5.0.4 on 2024-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_dislikes_comment_reaction_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
