# Generated by Django 5.0.4 on 2024-05-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('review', '0003_alter_review_dislikes_alter_review_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
