# Generated by Django 5.0.4 on 2024-05-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_content_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
