# Generated by Django 5.0.4 on 2024-05-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
    ]
