# Generated by Django 5.0.4 on 2024-06-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_reaction_unique_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='dislike',
        ),
    ]
