# Generated by Django 5.0.4 on 2024-06-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_review_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('popular', '-time_stamp')},
        ),
        migrations.CreateModel(
            name='Review_visit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='review.review')),
            ],
        ),
    ]
