# Generated by Django 5.0.4 on 2024-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_alter_review_options_review_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
