# Generated by Django 5.0.4 on 2024-06-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_reaction_time_stamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-time_stamp',)},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_movie_user_review',
        ),
        migrations.AddField(
            model_name='review',
            name='again',
            field=models.BooleanField(default=False),
        ),
    ]
