# Generated by Django 5.0.4 on 2024-06-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testwebjob', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestWJ',
        ),
    ]
