# Generated by Django 5.0.4 on 2024-06-10 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_user_follow'),
        ('movies', '0039_remove_movie_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_movie', to='movies.movie'),
        ),
    ]
