# Generated by Django 5.0.4 on 2024-06-10 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_movie'),
        ('review', '0010_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_activity', to='review.review'),
        ),
    ]
