# Generated by Django 5.0.4 on 2024-05-01 16:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='also_known_as',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100),
                                                                     size=None), blank=True, null=True, size=None),
        ),
    ]
