# Generated by Django 5.0.4 on 2024-05-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_also_known_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='also_known_as',
        ),
    ]
