# Generated by Django 5.0.4 on 2024-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_person_also_known_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
