# Generated by Django 5.0.4 on 2024-05-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0005_alter_person_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_path',
            field=models.ImageField(default='default.jpg', null=True, upload_to='pictures'),
        ),
    ]
