# Generated by Django 5.0.4 on 2024-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_person_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
