# Generated by Django 5.0.4 on 2024-05-03 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0021_delete_cast'),
        ('people', '0010_alter_person_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
