# Generated by Django 5.0.4 on 2024-05-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0011_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(default=False)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='others', max_length=20)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('known_for_department', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=200, null=True)),
                ('profile_path', models.ImageField(default='default.jpg', null=True, upload_to='pictures')),
            ],
        ),
    ]
