# Generated by Django 5.0.4 on 2024-05-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_person_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_path',
            field=models.TextField(default='default.jpg'),
        ),
    ]
