# Generated by Django 5.0.4 on 2024-04-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('homepage', models.CharField(blank=True, max_length=200, null=True)),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=200)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField()),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
