# Generated by Django 5.0.4 on 2024-04-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0003_alter_movies_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='revenue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
