# Generated by Django 5.0.4 on 2024-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_budget_alter_movies_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
