# Generated by Django 5.0.4 on 2024-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0005_alter_movies_budget_alter_movies_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
