# Generated by Django 5.0.4 on 2024-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0006_alter_movies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='budget',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='revenue',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='tagline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
