# Generated by Django 5.0.4 on 2024-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('movies', '0007_alter_movies_budget_alter_movies_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(blank=True, to='genres.genrers'),
        ),
    ]
