# Generated by Django 5.0.4 on 2024-04-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('movies', '0008_movies_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='genres.genrers'),
        ),
    ]
