# Generated by Django 5.0.4 on 2024-04-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_rename_genrers_genre'),
        ('movies', '0010_rename_movies_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='genres.genre'),
        ),
    ]
