# Generated by Django 5.0.4 on 2024-04-30 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0013_alter_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
    ]
