# Generated by Django 5.0.4 on 2024-05-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0015_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
