# Generated by Django 5.0.4 on 2024-05-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0016_alter_movie_backdrop_path_alter_movie_poster_path'),
        ('people', '0010_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charactor', models.CharField(max_length=200, null=True)),
                ('cast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts',
                                               to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='movies', through='movies.Cast', to='people.person'),
        ),
    ]
