# Generated by Django 5.0.4 on 2024-05-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_cast_movie_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='cast_id',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
