# Generated by Django 5.0.4 on 2024-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_rename_cast_id_cast_cast_rename_movie_id_cast_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
