# Generated by Django 5.0.4 on 2024-05-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_alter_cast_charactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='charactor',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
