# Generated by Django 5.0.4 on 2024-05-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_alter_cast_charactor'),
        ('people', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_movies', to='people.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='cast_movies', through='movies.Cast', to='people.person'),
        ),
    ]
