# Generated by Django 5.0.4 on 2024-05-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0029_remove_movie_director'),
        ('people', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors',
                                            to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director_movies', through='movies.Director', to='people.person'),
        ),
    ]
