# Generated by Django 5.0.4 on 2024-05-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0031_alter_movie_backdrop_path_alter_movie_poster_path'),
        ('people', '0013_alter_person_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person',
                                    to='people.person'),
        ),
    ]
