# Generated by Django 5.0.4 on 2024-05-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_rename_cast_movie_casts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-release_date',)},
        ),
    ]
