# Generated by Django 5.0.4 on 2024-05-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_rename_charactor_cast_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(null=True),
        ),
    ]
