# Generated by Django 5.0.4 on 2024-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0039_remove_movie_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popular',
            field=models.FloatField(default=0),
        ),
    ]
