# Generated by Django 5.0.4 on 2024-06-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0040_movie_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('popular', '-release_date')},
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='movies.movie')),
            ],
        ),
    ]
