# Generated by Django 5.0.4 on 2024-06-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0041_alter_movie_options_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='movies.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
