# Generated by Django 5.0.4 on 2024-06-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0042_visit_delete_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
